# Generated by Django 5.2.5 on 2026-03-30 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_object_id", models.PositiveBigIntegerField()),
                (
                    "channel_type",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Channel Type"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Email address, phone number, chat id or etc ...",
                        max_length=255,
                        verbose_name="Destination",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower value means higher priority"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="True when recipient has confirmed this channel",
                        verbose_name="Is Verified",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Recipient Content Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Channel",
                "verbose_name_plural": "Notification Channels",
                "indexes": [
                    models.Index(
                        fields=[
                            "recipient_content_type",
                            "recipient_object_id",
                            "channel_type",
                        ],
                        name="Notificatio_recipie_7e6b7a_idx",
                    ),
                    models.Index(
                        fields=[
                            "recipient_content_type",
                            "recipient_object_id",
                            "is_primary",
                        ],
                        name="Notificatio_recipie_0025ec_idx",
                    ),
                    models.Index(
                        fields=[
                            "recipient_content_type",
                            "recipient_object_id",
                            "priority",
                        ],
                        name="Notificatio_recipie_37e0bb_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("recipient_content_type", "recipient_object_id"),
                        name="unique_primary_channel_per_recipient",
                    )
                ],
                "unique_together": {
                    (
                        "recipient_content_type",
                        "recipient_object_id",
                        "channel_type",
                        "identifier",
                    )
                },
            },
        ),
    ]
