# Generated by Django 5.2.5 on 2026-03-30 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotificationApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannelVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="NotificationApp.notificationchannel",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token"], name="Notificatio_token_733f3c_idx")
                ],
            },
        ),
    ]
