# Generated by Django 5.2.5 on 2025-09-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotificationApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationmethod",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Is Primary"),
        ),
        migrations.AlterField(
            model_name="notificationmethod",
            name="method_type",
            field=models.CharField(
                choices=[("email", "Email"), ("sms", "SMS")],
                max_length=20,
                verbose_name="Method Type",
            ),
        ),
    ]
