# Generated by Django 5.2.5 on 2026-03-22 05:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NotificationApp", "0002_notificationmethod_is_primary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NotificationMethod",
            new_name="NotificationChannel",
        ),
    ]
