# Generated by Django 5.2.5 on 2026-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotificationApp", "0002_notificationchannelverification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationchannelverification",
            options={
                "verbose_name": "Notification Channel Verification",
                "verbose_name_plural": "Channel Verification Tokens",
            },
        ),
        migrations.AlterField(
            model_name="notificationchannelverification",
            name="token",
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
        migrations.AddConstraint(
            model_name="notificationchannelverification",
            constraint=models.UniqueConstraint(
                fields=("channel", "token"), name="unique_channel_token"
            ),
        ),
    ]
