# Generated by Django 5.2.5 on 2026-03-22 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotificationApp", "0003_rename_notificationmethod_notificationchannel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationchannel",
            name="channel_type",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Channel Type"
            ),
        ),
        migrations.AddField(
            model_name="notificationchannel",
            name="priority",
            field=models.PositiveIntegerField(
                default=100, help_text="Lower value means higher priority"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationchannel",
            unique_together={("user", "channel_type", "identifier")},
        ),
    ]
