# Generated by Django 5.2.5 on 2026-04-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "NotificationApp",
            "0003_alter_notificationchannelverification_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationchannelverification",
            name="unique_channel_token",
        ),
        migrations.RemoveIndex(
            model_name="notificationchannelverification",
            name="Notificatio_token_733f3c_idx",
        ),
        migrations.AddField(
            model_name="notificationchannelverification",
            name="selector",
            field=models.CharField(db_index=True, default="__default__", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificationchannelverification",
            name="token",
            field=models.CharField(max_length=128),
        ),
        migrations.AddIndex(
            model_name="notificationchannelverification",
            index=models.Index(
                fields=["channel", "is_used", "expires_at"],
                name="Notificatio_channel_9b98aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationchannelverification",
            index=models.Index(
                fields=["selector"], name="Notificatio_selecto_fcc109_idx"
            ),
        ),
    ]
