# Generated by Django 5.2.5 on 2026-03-23 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotificationApp", "0004_alter_notificationchannel_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationchannel",
            options={
                "verbose_name": "Notification Channel",
                "verbose_name_plural": "Notification Channels",
            },
        ),
        migrations.RemoveField(
            model_name="notificationchannel",
            name="method_type",
        ),
        migrations.AlterField(
            model_name="notificationchannel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_channels",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationchannel",
            index=models.Index(
                fields=["user", "channel_type"], name="Notificatio_user_id_c4001d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationchannel",
            index=models.Index(
                fields=["user", "is_primary"], name="Notificatio_user_id_5eb4c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationchannel",
            index=models.Index(
                fields=["user", "priority"], name="Notificatio_user_id_bb23c7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationchannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("user",),
                name="unique_primary_channel_per_user",
            ),
        ),
    ]
