# Generated by Django 5.2.5 on 2026-04-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "NotificationApp",
            "0004_remove_notificationchannelverification_unique_channel_token_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selector", models.CharField(db_index=True, max_length=64)),
                ("token_hash", models.CharField(max_length=128)),
                ("purpose", models.CharField(db_index=True, max_length=64)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Notification Token",
                "verbose_name_plural": "Notification Tokens",
                "indexes": [
                    models.Index(
                        fields=["selector"], name="Notificatio_selecto_807b25_idx"
                    ),
                    models.Index(
                        fields=["purpose", "is_used", "expires_at"],
                        name="Notificatio_purpose_6bdb6a_idx",
                    ),
                ],
            },
        ),
        migrations.DeleteModel(
            name="NotificationChannelVerification",
        ),
    ]
