# Generated by Django 5.2.5 on 2026-04-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotificationApp", "0005_notificationtoken_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_links",
                        to="NotificationApp.notificationchannel",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_links",
                        to="NotificationApp.notificationtoken",
                    ),
                ),
            ],
            options={
                "unique_together": {("token", "channel")},
            },
        ),
    ]
