# Generated by Django 5.2.5 on 2026-04-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotificationApp", "0006_channelverificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelverificationtoken",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="token_links",
                to="NotificationApp.notificationchannel",
            ),
        ),
        migrations.AlterField(
            model_name="channelverificationtoken",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_links",
                to="NotificationApp.notificationtoken",
            ),
        ),
        migrations.AddIndex(
            model_name="channelverificationtoken",
            index=models.Index(
                fields=["channel"], name="Notificatio_channel_ded8bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelverificationtoken",
            index=models.Index(fields=["token"], name="Notificatio_token_i_13dd7e_idx"),
        ),
    ]
