# Generated by Django 5.2.5 on 2025-09-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0020_auto_20250829_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=523495),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='bb50569557ce3b6d7a63c19c14e644dc9cd0f5e4dab1726056073830e50ffa269dbb2b4fab98430568ae0eabf34497aa3623adbb431572cf7c9e1628a9a17253', max_length=64),
        ),
    ]
