# Generated by Django 3.2.8 on 2025-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0014_auto_20240104_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=710203),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='63ed6c06651d400fa894da261ba0658c74d1c402497a6668601fee06432730243d1cc484e44560d4111422772f7fd462ee3189446eaf41444ae41386a881fd77', max_length=64),
        ),
    ]
