# Generated by Django 3.2.8 on 2025-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0015_auto_20250824_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=358970),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='b64b72fe09f7bd2ed07fbd55c4518ec9a6d396ac641670f5fea80f2ffba6e5f18be3e6d169b56a6c9d83eca928a3436c64d7f510ad559e181fea26de4d953b5c', max_length=64),
        ),
    ]
