# Generated by Django 3.2.8 on 2025-08-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0016_auto_20250824_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=707176),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='d3adedbbe6687b7f6dbf7b2a8eb0ada8571346759e7f23de05949f763a80066ade24675a0b71405d3526230854a7341b72936ac196d4deb1f7136ba88f881ae7', max_length=64),
        ),
    ]
