# Generated by Django 3.2.8 on 2025-08-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0017_auto_20250824_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=913341),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='b9d0d7f55ed46878998dd4e3cdb955459769cdeb8da7e93cc08ab7bb9e4583d43556953e47d81ebcab3f5c10203c6360107ae589ca48a14a836d435e1b3fe9be', max_length=64),
        ),
    ]
