# Generated by Django 3.2.8 on 2025-08-29 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0019_auto_20250824_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='partner_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ReportApp.person'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='partner_spend',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ReportApp.spend'),
        ),
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spenders',
            name='spender_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ReportApp.person'),
        ),
        migrations.AlterField(
            model_name='spenders',
            name='spender_spend',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ReportApp.spend'),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=473973),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='48f92bd14de802f4cc637866f61d29d8d0fe62804cb9973f74851fea2007036a88b0b546ec6697f640225889ba6b775311a813565233694a365069686af6649d', max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='ReportApp.person'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='ReportApp.person'),
        ),
    ]
