# Generated by Django 5.2.5 on 2025-09-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0021_alter_token_reset_pass_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
