# Generated by Django 3.2.5 on 2021-09-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name_plural': 'partner (Person m2m Spend)'},
        ),
        migrations.AlterModelOptions(
            name='spenders',
            options={'verbose_name_plural': 'spender (Person m2m Spend)'},
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
