# Generated by Django 3.2.5 on 2021-10-14 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0002_auto_20211011_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': '    Persons'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': '     Rooms'},
        ),
        migrations.AlterModelOptions(
            name='spend',
            options={'verbose_name_plural': '  Spends'},
        ),
        migrations.AlterModelOptions(
            name='spenders',
            options={'verbose_name_plural': ' spender (Person m2m Spend)'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name_plural': '      Tokens'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': '   Transactions'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '       Users'},
        ),
        migrations.AlterField(
            model_name='person',
            name='verify_email_token',
            field=models.CharField(default='d63c4300a8a6e64ce4c370e3b43855d244dfe0c8f19413d505ad6d6ec806d7f06784b1aa45415940f2ae9bfff6282b6528b195a3f39e253185e2e96c99776053', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='verify_phone_code',
            field=models.IntegerField(default=757836),
        ),
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=218347),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='90b8467973d1c65bcbc9f002c49871e00e048cd0c1502b24302772ae464fea17a24285c5145747e6b0268981fcffe0f2be15e7281d5ff0be900f1453bc1561a8', max_length=64),
        ),
    ]
