# Generated by Django 3.2.5 on 2021-10-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0002_auto_20210924_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='person',
            name='spenders',
        ),
        migrations.RemoveField(
            model_name='spend',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='spend',
            name='spenders',
        ),
        migrations.AddField(
            model_name='partners',
            name='partner_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='AccountingApp.person'),
        ),
        migrations.AddField(
            model_name='partners',
            name='partner_spend',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='AccountingApp.spend'),
        ),
        migrations.AddField(
            model_name='spenders',
            name='spender_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='AccountingApp.person'),
        ),
        migrations.AddField(
            model_name='spenders',
            name='spender_spend',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='AccountingApp.spend'),
        ),
    ]
