# Generated by Django 3.2.5 on 2021-10-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0003_auto_20211014_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='verify_email_token',
            field=models.CharField(default='47985abcfe991ee27a17602a03ae960a0eaf295204c9a138de96ede612b654d2a16125d6ee55cd7730889b1cd5036bd474ebb9929f094b67d1f69fd3345d857e', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='verify_phone_code',
            field=models.IntegerField(default=868624),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=950986),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='9d2660432a49de055227f3162bd4810dbc51aae1b3fd3020e06095ffa494975fc90fb3e165f6d8b336933461d4ce30d0158d0a08f58aed6502b1ed36d1665ba2', max_length=64),
        ),
    ]
