# Generated by Django 3.2.5 on 2021-10-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0003_auto_20211002_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
