# Generated by Django 3.2.5 on 2021-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0004_auto_20211014_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='verify_email_token',
            field=models.CharField(default='3f1e793b099c8e1acb4713a5738df9bff4524af4e55ce04048d1a031c90f87221a865e82e4b3c16194abc23b5e014f7454ba34185a0255d66ed1be5e8d807043', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='verify_phone_code',
            field=models.IntegerField(default=228879),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=254219),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='e7357c88af41d95c3bde59b28e72b2b4458e5d1f2728a2b3c246fa48223050343abeedce9aceb8a95ca61794d6c71df03e5f5764c35d974fd0375e0202676337', max_length=64),
        ),
    ]
