# Generated by Django 3.2.5 on 2021-10-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0004_spend_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spend',
            old_name='created_at',
            new_name='date',
        ),
    ]
