# Generated by Django 3.2.5 on 2021-10-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0005_auto_20211017_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='verify_email_token',
            field=models.CharField(default='db2fe19734c31f307e5289be5b47f1857c8c07f7ca7281fd6114b684dd429be2fc0dfedd310716575a0c263eae35738495936ecca12da3f637f5fd53200623f8', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='verify_phone_code',
            field=models.IntegerField(default=622076),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=798616),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='8a36e9ebdde2cfb05dcc601332baeb2abb1d204a79443c2cb3cfbe95fbfa7e44de43a7b6cf4b69a5bc3ae1a2c543a84a76a5239e229caed792ede2b8432e2bce', max_length=64),
        ),
    ]
