# Generated by Django 3.2.5 on 2021-10-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0006_auto_20211017_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='verify_email_token',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='verify_phone_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=188521),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='c7f0d9a97d47e6407271a4bd481b73575261a0cec619ff248eab7a5d4ae2b2192ec47bc1b3a154e03659be42963f0c7e6985412469ed8f5f78667ac6324f5fa9', max_length=64),
        ),
    ]
