# Generated by Django 3.2.5 on 2021-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0007_auto_20211019_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=269398),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='a11f7656e60eab50885f0e92ed395403bf8b9d70923ea76769226b7236ba3fcbada482d7635e269a5edb6871ffbfadfcfe7f6af5fff785bb585df3ca5d6422b4', max_length=64),
        ),
    ]
