# Generated by Django 3.2.8 on 2022-04-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0009_auto_20220406_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=231349),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='06ba37d3583a978a881d5d651f5ed6fd938a34d33a9fa307419673e58a128f7027947358e75ca991be6b7dc043f6fca18aecf92f9ffcc3a5f19936616595915f', max_length=64),
        ),
    ]
