# Generated by Django 3.2.8 on 2023-06-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0010_auto_20220406_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=971680),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='94f8f63c439ed18cc72f521fb7f7f5564b19f5674f2eb99a8d16df12a1fabf034490de7dec522f5f68b672ae0d39662489be0f9a31e99fe92f0e76b7684dcf4c', max_length=64),
        ),
    ]
