# Generated by Django 3.2.8 on 2024-01-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0011_auto_20230605_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=533960),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='d036d94f3ac3a0812ef26544c1ce62ac0aedb3130127f2167810ba0506c3313678c5ecd32e0ccd48afcfda95130bbec6613b55e151719f51955b7bb5b8a281d9', max_length=64),
        ),
    ]
