# Generated by Django 3.2.8 on 2024-01-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0012_auto_20240104_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=809593),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='9911c86e0cbdd9c932a1ebea232b99d37d74115c1c90ac2faeb35fa22284365a235c558a7aea12986abaec87f742fcb2bd1f7977134d23e7ccc58621837e96e3', max_length=64),
        ),
    ]
