# Generated by Django 3.2.8 on 2024-01-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountingApp', '0013_auto_20240104_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=984603),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='227d9fcad114d94f05cdafa1e7ca53da6ed21710d94b2ac7abcb1fb4e4815e0dd6101b22f3f4d6e3ea6108e6b3f4ca9e986a71af976bf07c76192afaba0a0a66', max_length=64),
        ),
    ]
