# Generated by Django 5.2.5 on 2025-09-20 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=20,
                        verbose_name="Method Type",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Email address, phone number, chat id or etc ...",
                        max_length=255,
                        verbose_name="Destination",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="True when user has confirmed this channel",
                        verbose_name="Is Verified",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_methods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Method",
                "verbose_name_plural": "Notification Methods",
                "unique_together": {("user", "method_type", "identifier")},
            },
        ),
    ]
