# Generated by Django 5.2.5 on 2026-04-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ReportApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
    ]
