# Generated by Django 5.2.5 on 2026-04-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ReportApp", "0002_remove_user_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
