# Generated by Django 5.2.5 on 2026-04-28 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReportApp", "0004_person_user_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
