# Generated by Django 5.2.5 on 2026-04-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ReportApp", "0005_alter_person_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("room_owner", "RoomOwner"), ("person", "Person")],
                db_index=True,
                default="owner_owner",
                max_length=10,
            ),
        ),
    ]
