# Generated by Django 5.2.5 on 2026-04-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ReportApp", "0006_alter_user_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
