# Generated by Django 3.2.8 on 2025-08-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportApp', '0018_auto_20250824_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='reset_pass_code',
            field=models.IntegerField(default=905401),
        ),
        migrations.AlterField(
            model_name='token',
            name='reset_pass_token',
            field=models.CharField(default='f6932dd832839cc17bc48217006cb63ec27fee140c232bb1b3e2e85d645b47174e0eed9372bd3e8f56d33f82fe02209a1cc0f2c236f6d8ea7c919bba1a9bb4b6', max_length=64),
        ),
    ]
